version: 2

defaults: &defaults
    working_directory: ~/repo
    docker:
        - image: circleci/node:10.13

jobs:
    test:
        <<: *defaults
        steps:
            - checkout

            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-

            - run: npm install

            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}

            - run:
                name: Run tests
                command: npm test

            - persist_to_workspace:
                root: ~/repo
                paths: .

    deploy:
        <<: *defaults
        steps:
            - attach_workspace:
                at: ~/repo

            - run:
                name: Authenticate with registry
                command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc

            - run:
                name: Publish package
                command: npm publish

    docs-build:
        <<: *defaults
        steps:
            - checkout

            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-

            - run: npm install

            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}

            - run:
                name: Build docs
                command: npm run docs:build

            - persist_to_workspace:
                root: ~/repo/docs/.vuepress
                paths: .

    docs-deploy:
        <<: *defaults
        steps:
            - attach_workspace:
                at: ~/repo/docs/.vuepress

            - run:
                name: install gh-pages
                command: npm install -g --silent gh-pages@2.0.1

            - run:
                name: Configure dependencies
                command: |
                    git config user.email "nevos12@gmail.com"
                    git config user.name "Nevo"

            - run:
                name: Deploy docs to gh-pages branch
                command: gh-pages --dist ~/repo/docs/.vuepress/dist


workflows:
    version: 2
    test-deploy:
        jobs:
            - test:
                filters:
                    tags:
                        only: /^v.*/
            - deploy:
                requires:
                    - test
                filters:
                    tags:
                        only: /^v.*/
                    branches:
                        ignore: /.*/

    docs:
        jobs:
            - docs-build:
                filters:
                    branches:
                        only: master
            - docs-deploy:
                requires:
                    - docs-build
                filters:
                    branches:
                        only: master
